---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: production
  labels:
    app: postgres
    environment: production
type: Opaque
data:
  # Base64 encoded values
  # POSTGRES_USER: myuser (bXl1c2Vy)
  # POSTGRES_PASSWORD: mypassword123 (bXlwYXNzd29yZDEyMw==)
  # POSTGRES_DB: myapp (bXlhcHA=)
  POSTGRES_USER: bXl1c2Vy
  POSTGRES_PASSWORD: bXlwYXNzd29yZDEyMw==
  POSTGRES_DB: bXlhcHA=
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: production
  labels:
    app: backend
    environment: production
type: Opaque
data:
  # Base64 encoded values
  # JWT_SECRET: jwt-super-secret-key-12345 (and0LXN1cGVyLXNlY3JldC1rZXktMTIzNDU=)
  # DB_PASSWORD: mypassword123 (bXlwYXNzd29yZDEyMw==)
  JWT_SECRET: and0LXN1cGVyLXNlY3JldC1rZXktMTIzNDU=
  DB_PASSWORD: bXlwYXNzd29yZDEyMw==
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: production
  labels:
    app: ingress
    environment: production
type: kubernetes.io/tls
data:
  # Self-signed certificate (in production, use cert-manager)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMakNDQWhZQ0NRREFPRjl0THNQVmFEQU5CZ2txaGtpRzl3MEJBUXNGQURCWU1Rc3dDUVlEVlFRR0V3SlYKVXpFTk1Bc0dBMVVFQ0F3RVUzUmhkR1V4RGpBTUJnTlZCQWNNQlU1bGR5QlpNUkV3RHdZRFZRUUtEQWhOZVVOdgpjbkF4Q3pBSkJnTlZCQXNNQWtOQk1Sc3dHUVlEVlFRRERCSnRlV0Z3Y0M1c2IyTmhiQzVqYjIwd0hoY05NakF3Ck16SXhNVFEwTWpNeFdoY05NakV3TXpJeE1UUTBNak14V2pCWU1Rc3dDUVlEVlFRR0V3SlZVekVOTUFzR0ExVUUKQ0F3RVUzUmhkR1V4RGpBTUJnTlZCQWNNQlU1bGR5QlpNUkV3RHdZRFZRUUtEQWhOZVVOdmNuQXhDekFKQmdOVgpCQXNNQWtOQk1Sc3dHUVlEVlFRRERCSnRlV0Z3Y0M1c2IyTmhiQzVqYjIwd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEak5FQXA1SWV6TDNBWWVUWVIrSGpzOEJDSDZiUHUyUnRIbC9ZcjgzN0wKVGk0bWZFSmRvTW9mTk9lQWNyTE5hYmZPSnJneFFkNEVSeHBDVGxWZzNqQlBBbEt2dE1HTENJQzNidHdBWU5YbApVUGFCTEYzYXhYT21wekNkUCtRNnZpaGdGNzU0a0QyT1hCaGJYSHEzazFZSmNzNTFSeGF5N3hFaW9zSjFWWVRECkNTMVlxdVBaWlZvbDc1M0lwUGJkQ1ZzYm51am9OdC81c2liY3JsaUhDcHNmNHl3bmVkWFFITjZhODBsY0grckkKMjNIL1V0d2ZhbjhxZGN5RHlNZXprMGIxQkpoelJiZ0l3cUVlOWs1aG1mTW9GN2ZhWTNvbGNieDBGUWVJejhnYwpKU3lhVE5HUklydjV6UzVJTjUxY0JCaE1uZzd3NXBKdWxJQldxRmdwbHA5bkFnTUJBQUV3RFFZSktvWklodmNOCkFRRUxCUUFEZ2dFQkFOZHdnV0Q0NlFBQUlFM2JZSlZMTGthZ1k4NFlwNXBvb0txRGhySjUzRUFPWFYzSldMQ0cKSGVwbHpEQ0kxbjNOSzVaL0NtUm1LdUlsaXl0bWpnV01GRUY4THd3R2IrT2xTdnZnNnVIQUxabm1JQVBLdnpMQgovNThJU1pUcWh0dDVzZU1yb3NNRG1OV2FrZWVwdXhDZmJYRFZPTGxuLzVJMXZZNVEzWVNvZUNxRjhCSmRHa25rCkRVSjNxdFJOV0NEMVZZQlhoSGkwZFdLUXdNUVFoQTA1ZnRGQ0JrWUlFU0VEa2NQUW00TG5sZkZJSVJRU3Mrb2cKajVGSG5EcEVjSFRkbm9oY2hzS2Z0cjFHZk1uU3Z3K3BjVFMrU0tzL0xCZEQrL0J6bFE4cGRoeE53d3hJYzJPaApNVjYxWGJrWko1d2NwVjFWdnNaK3JPVlhvVjFua2ZNSFZiUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRGpORUFwNUllek1qQWoKWWVUWVIrSGpzOEJDSDZiUHUyUnRIbC9ZcjgzN0xUaTRtZkVKZG9Nb2ZOT2VBY3JMTmFiZk9Kcmd4UWQ0RVJ4cApDVGxWZzNqQlBBbEt2dE1HTENJQzNidHdBWU5YbFVQYUJMRjNheFhPbXB6Q2RQK1E2dmloxMhGNzU0a0QyT1hCCmhiWEhxM2sxWUpjczUxUnhheTd4RWlvc0oxVllURENTMVlxdVBaWlZvbDc1M0lwUGJkQ1ZzYm51am9OdC81c2kKYmNybGlIQ3BzZjR5d25lZFhRSE42YTgwbGNIK3JJMjNIL1V0d2ZhbjhxZGN5RHlNZXprMGIxQkpoelJiZ0l3cQpFZTlrNWhtZk1vRjdmYVkzb2xjYngwRlFlSXo4Z2NKU3lhVE5HUklydjV6UzVJTjUxY0JCaE1uZzd3NXBKdWxJCkJXcUZncGxwOW5BZ01CQUFFQ2dnRUJBSU80RGxvSk1OTWtCUjE1M0JUcjI1QjM5NzZNZUFQbFd2Q2Q2N3pBNVUKRGdRaUxvNEVhRmhPZWQ5dzR5TVRDK1dvaGpGSjJoTzl3OHdTaWJ2M3lWbE5RY3VFZmR3Z3pxYng4VzlOUEI1NApvZUVGN2N3aUFEeGNZTCtKQ29wZENnUE4xRExDZWJzZkZwOUhGN0l3dXZJWGNwRWQ0cERYRmtKNk92NzRicnpOCiswOWN5Rk5kWUFON2FBcVJRRGtaelRtMGlqNWFLek1iQTRjWVVaS2s5TzZJNXFGUTAyMkNRUnNOWU5EOGFJZVUKMGVUQmFxWUg2cllpSm9wWkNjZXlxWHljMERRdURJZEgxVlp6ZXRWMm5qY0luNzY3eHRCdGRVaElkdG0wRFlBcgpWZHhpSHJkdjVXSkxtVGdkUnBOY0FId2xLdUdJUWFNRkEwWi9rT2tDZ1lFQStsSUNQRjRWSGhCbWlZZU0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==
